
services:
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin123"
      POSTGRES_USER: "leandro"
      POSTGRES_DB: "otrack"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
