/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export type PostUsers201Roule = typeof PostUsers201Roule[keyof typeof PostUsers201Roule];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostUsers201Roule = {
  ADMIN: 'ADMIN',
  LOG: 'LOG',
  TECHNIC: 'TECHNIC',
} as const;
