/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { PostUsers201Roule } from './postUsers201Roule';

/**
 * Created User
 */
export type PostUsers201 = {
  id: number;
  displayName: string;
  username: string;
  password: string;
  roule: PostUsers201Roule;
};
