/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export type PostUsersBodyRoule = typeof PostUsersBodyRoule[keyof typeof PostUsersBodyRoule];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostUsersBodyRoule = {
  ADMIN: 'ADMIN',
  LOG: 'LOG',
  TECHNIC: 'TECHNIC',
} as const;
