/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { PostUsersBodyRoule } from './postUsersBodyRoule';

export type PostUsersBody = {
  displayName: string;
  username: string;
  password: string;
  roule: PostUsersBodyRoule;
};
