export enum SignInExceptions {
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR'
}

export enum TokenExceptions {
  INVALID_TOKEN = 'INVALID_TOKEN',
  EXPIRES_TOKEN = 'EXPIRES_TOKEN'
}

export enum AuthException {
  UNAUTHORIZED = 'UNAUTHORIZED',
  UNAUTHENTICATED = 'UNAUTHENTICATED'
}


